baseURL = "https://me.david74.dev/"
languageCode = "en"
title = "David Chou"
theme = "hugo-devresume-theme"
googleAnalytics = "UA-XXXXXXX-Y"

[params]
    author = "David Chou"
    primaryColor = "#54B689"
    textPrimaryColor = "#292929"

    [params.profile]
        enable = true
        name = "David Chou"
        tagline = ""
        description = "Golang developer, DevOps engineer, Community participant"
        avatar = "avatar.png"

    [params.contact]
        enable = true

        [[params.contact.list]]
        icon = "fas fa-envelope"
        url = "mailto:david74.chou@gmail.com"
        text = "david74.chou@gmail.com"
        [[params.contact.list]]
        icon = "fab fa-linkedin"
        url = "https://www.linkedin.com/in/ting-li-chou-55393662/"
        text = "Ting-Li Chou"
        [[params.contact.list]]
        icon = "fab fa-github"
        url = "https://github.com/david7482"
        text = "github.com/david7482"
        [[params.contact.list]]
        icon = "fab fa-medium"
        url = "https://blog.david74.dev"
        text = "blog.david74.dev"
        [[params.contact.list]]
        icon = "fab fa-slideshare"
        url = "https://speakerdeck.com/david74chou"
        text = "speakerdeck.com/david74chou"

    [params.summary]
    enable = true
    text = """As a developer team lead of a startup, I lead the team to build our SaaS product from 0 to 1
    and is driven to keep the company growing by offering compelling new features and services to our customers.
    \nI am an experienced Golang developer and built several production services in Golang, and a DevOps engineer
    with experience in AWS, Terraform, and Kubernetes. To boost the efficiency of the team, I standardized the process
    of CI/CD, deployment, monitoring, alerting of our services, and shaped the DevOps culture among members.
    \nI love to participate in community activities and also share my knowledge with [blogs](https://blog.david74.dev) and
    [technical talks](https://speakerdeck.com/david74chou). Currently, I am the co-organizer of the Golang Taiwan community.
    """

    [params.education]
        enable = true

        [[params.education.list]]
        degree = "M.S in Computer Science"
        university = "National Chiao Tung University"
        dates = "2007 - 2009"
        [[params.education.list]]
        degree = "B.S in Computer Science"
        university = "National Chiao Tung University"
        dates = "2003 - 2007"

    [params.awards]
        enable = true

        [[params.awards.list]]
        name = "Publications"
        body = "[Scene change aware intra-frame rate control for H.264/AVC](https://ieeexplore.ieee.org/document/5604298)"
        date = "IEEE TCSVT, 2010"
        [[params.awards.list]]
        name = "Patents"
        body = "[System and method for streaming media](https://twpat-simple.tipo.gov.tw/tipotwoc/tipotwkm?!!FR_201916664)"
        date = "Taiwan invention patent"

    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "Chinese"
        level = "Native"
        [[params.languages.list]]
        name = "English"
        level = "Fluent"

    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Developer Team Lead"
        dates = "2015 - 2021"
        company = "Umbo"
        details = """Umbo is an A.I. startup that leverages machine learning and cloud technology to build
        autonomous video security systems for businesses. As a founding engineer, I participated in the whole
        architecture design and product implementation from scratch.
        """
        [[params.experience.list.items]]
        details = "Team management"
        [[params.experience.list.items.subs]]
        details = """**Led developer team of 8 members**. My responsibilities included OKR planning, regular 1-1
        feedback, mentoring, sponsoring, and hiring.
        """
        [[params.experience.list.items.subs]]
        details = """**Frequently co-worked with different teams**, such as Design, Product, ML and Sales teams, to discuss
        items from product roadmap, feature specs to customer complains and service integration details.
        """
        [[params.experience.list.items.subs]]
        details = """**Focused on increasing team-wise productivity** by standardlizing development flow, introducing CI/CD
        and unit testing, consistent service deployment flow, shaping DevOps culture, etc.
        """
        [[params.experience.list.items]]
        details = "Architect and engineering"
        [[params.experience.list.items.subs]]
        details = """Designed and developed a **low latency video streaming service** in Golang on a large scale
        across multiple regions. It became the core architecture of Umbo's streaming-based product and served more
        than 7500 online cameras with below 3 seconds end-to-end latency.
        """
        [[params.experience.list.items.subs]]
        details = """Developed and maintained the core **IoT messaging service** in Golang. Packaged with Docker and
        deployed with Ansible. It provided real-time communication with devices by WebSocket and served all Umbo's
        cameras across 4 different regions.
        """
        [[params.experience.list.items.subs]]
        details = """Involved in **firmware architecture design and development**, including firmware services, IPC protocol,
        and service configuration. Designed a flexible cross-platform firmware architecture that helps us to deliver
        different camera models efficiently.
        """
        [[params.experience.list.items.subs]]
        details = """Developed a **Windows-based service** in Golang. It bridged Umbo alerts into 3rd-party systems under
        a constrained network environment. I packaged the installation process into wizard that set up auto-start,
        restart-on-failure, and log sidecar. This project helped Umbo win 2 enterprise customers.
        """
        [[params.experience.list.items.subs]]
        details = """Involved in the design and development of Umbo’s **Event-Filter product**. Event-Filter is aimed to
        optimize customer’s human resources by filtering out false alerts generated from their own devices.
        I implemented **2 gateway services (SMTP and HTTP)** in Golang and deployed them to ECS Fargate with Terraform.
        As a result, Event-Filter reduced 83% of false alarms for customers and boosted Umbo’s monthly recurring
        revenue (MRR) by 230% in a year.
        """
        [[params.experience.list.items]]
        details = "Infrastructure and process optimization"
        [[params.experience.list.items.subs]]
        details = """**Standardlized Umbo’s production service deployment** by using AWS ECS Fargate and Terraform. With
        this consistent setup, different services would use the same way for secret management, log collection, monitoring,
        tracing, etc. It drastically reduced the loading of operation and speeded up the launch of new services by 300%.
        """
        [[params.experience.list.items.subs]]
        details = """Led and supported the team to continuously **reduce AWS infrastructure costs**. I regularly reviewed AWS cost analysis
        and proposed different approaches for cost reduction, including NAT traffic reduction, EC2/Fargate Spot adoption,
        EC2 ARM instance adoption, cross-zone traffic reduction, S3 lifecycle optimization, etc. As a result, we reduced
        54% unit cost by average.
        """
        [[params.experience.list.items.subs]]
        details = """**Migrated Umbo's internal services to EKS** by using Terraform and Helm. The internal services included
        Grafana, Fluentd aggregator, Metabase, ETL jobs, etc. I also **optimized the performance of the log collection pipeline**
        by fine-tuning Fluentd and ElasticSearch.
        """
        [[params.experience.list.items.subs]]
        details = """Led and supported the team to **build a cross-services tracing solution** by leveraging NewRelic tracing service.
        It gave us a clear view of end-to-end latency, and we built monitoring and alerting based on the metrics.
        """

        [[params.experience.list]]
        title = "Senior Engineer"
        dates = "2013 - 2015"
        company = "Trend Micro Inc."
        details = """Joined the new industrial control system (ICS) solution team in the early stage, and experienced
        the whole product development cycle from planning, development, shipping, and maintenance.
        """
        [[params.experience.list.items]]
        details = "[Trend Micro Safe Lock](https://www.trendmicro.com/zh_tw/business/products/user-protection/sps/endpoint/safe-lock.html)"
        [[params.experience.list.items.subs]]
        details = "A standalone system lockdown software for fixed-function devices."
        [[params.experience.list.items.subs]]
        details = "Developed the backend REST API service."
        [[params.experience.list.items]]
        details = "[Trend Micro Portable Security](https://www.trendmicro.com/ja_jp/business/products/user-protection/sps/endpoint/portable-security-3.html)"
        [[params.experience.list.items.subs]]
        details = "A malware scanning and cleanup tool for standalone PC or closed system."
        [[params.experience.list.items.subs]]
        details = "Designed and developed this product from the fundamental core module to user interface."

        [[params.experience.list]]
        title = "Senior Engineer"
        dates = "2009 - 2012"
        company = "CyberLink Corp."
        details = """I worked on video decoder and new features development for H.264, MPEG2, and VC1. The video
        decoder is the core module in the company and has been integrated into all products.
        """
        [[params.experience.list.items]]
        details = "Maintained the quality of video decoder module."
        [[params.experience.list.items]]
        details = "Performance tuning with SSE/Intrinsic **SIMD optimization**."
        [[params.experience.list.items]]
        details = "Developed hardware decoding for **H.264**, Motion JPEG decoding using **hardware acceleration**."

    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "[lambda-extension-log-shipper](https://github.com/david7482/lambda-extension-log-shipper)"
        meta = "Golang / Lambda"
        tagline = """Ship your Lambda logs directly to any destination and bypass Cloudwatch Logs. This is my
        **personal project** that works like a sidecar of the Lambda function. It would listen to your Lambda function
        logs by Lambda Logs API, so you could ship the logs to a custom destination without CloudWatch Logs
        and **save cost**.
        """

        [[params.projects.list]]
        title = "[terraform-provider-aws](https://github.com/hashicorp/terraform-provider-aws)"
        meta = "Golang / Terraform"
        tagline = """A well-known terraform plugin to provision AWS resources. I contributed the **EKS taint support**
        in the Managed Node Group resource.
        """

        [[params.projects.list]]
        title = "[telegraf](https://github.com/influxdata/telegraf)"
        meta = "Golang"
        tagline = """A popular opensource metrics collection agent from influxdata. I contributed a **performance optimization**
        in its AWS Cloudwatch integration.
        """

    [params.information]
        enable = true

        [[params.information.list]]
        title = "Development"
        [[params.information.list.items]]
        details = "**Languages:** Golang, C/C++, Java, C#"
        [[params.information.list.items]]
        details = "**Databases:** MySQL, MongoDB, etcd"
        [[params.information.list.items]]
        details = "**Protocols:** HTTP, Websocket, gRPC, SMTP"

        [[params.information.list]]
        title = "Operations"
        [[params.information.list.items]]
        details = "**AWS:** S3, EC2, ECS, EKS, SQS, VPC, IAM, Lambda, EventBridge, Cloudfront, etc"
        [[params.information.list.items]]
        details = "**Container Orchestration:** Kubernetes, ECS"
        [[params.information.list.items]]
        details = "**IaC:** Terraform, Helm, Packer, Ansible, Serverless"
        [[params.information.list.items]]
        details = "**CI/CD:** Jenkins, Github Action"
        [[params.information.list.items]]
        details = "**Logs:** Fluentd, Fluentbit, Elasticsearch, Kibana"
        [[params.information.list.items]]
        details = "**Metrics:** Telegraf, Prometheus, Grafana"

        [[params.information.list]]
        title = "Multimedia"
        [[params.information.list.items]]
        details = "**Codecs:** H.264"
        [[params.information.list.items]]
        details = "**Container:** MP4, fMP4"
        [[params.information.list.items]]
        details = "**Streaming:** RTSP, HLS, DASH"
        [[params.information.list.items]]
        details = "**Framework:** FFMPEG, Live555, GStreamer"
        [[params.information.list.items]]
        details = "**Acceleration:** DxVA, SIMD"

        [[params.information.list]]
        title = "Others"
        [[params.information.list.items]]
        details = "**Source Control:** Git, SVN"
        [[params.information.list.items]]
        details = "**Build System:** Make, CMake"
        [[params.information.list.items]]
        details = "**Project Management:** JIRA, Confluence, Trello"

    [params.footer]
        copyright = "David Chou"