baseURL = "https://me.david74.dev/"
languageCode = "en"
title = "David Chou"
theme = "hugo-devresume-theme"
googleAnalytics = "G-FPJMFH212V"
disableKinds = ["taxonomy", "term"]

[sitemap]
    changefreq = 'weekly'
    filename = 'sitemap.xml'
    priority = 0.5

[params]
    author = "David Chou"
    primaryColor = "#54B689"
    textPrimaryColor = "#292929"

    [params.profile]
        enable = true
        name = "David Chou"
        tagline = ""
        description = "Golang developer, DevOps engineer, Engineering team lead, Community participant"
        avatar = "avatar.png"

    [params.contact]
        enable = true

        [[params.contact.list]]
        icon = "fas fa-envelope"
        url = "mailto:david74.chou@gmail.com"
        text = "david74.chou@gmail.com"
        [[params.contact.list]]
        icon = "fab fa-linkedin"
        url = "https://www.linkedin.com/in/ting-li-chou/"
        text = "Ting-Li Chou"
        [[params.contact.list]]
        icon = "fab fa-github"
        url = "https://github.com/david7482"
        text = "github.com/david7482"
        [[params.contact.list]]
        icon = "fab fa-medium"
        url = "https://blog.david74.dev"
        text = "blog.david74.dev"
        [[params.contact.list]]
        icon = "fab fa-slideshare"
        url = "https://speakerdeck.com/david74chou"
        text = "speakerdeck.com/david74chou"
        [[params.contact.list]]
        icon = "fas fa-file-pdf"
        url = "https://me.david74.dev/david-chou.pdf"
        text = "pdf version"

    [params.summary]
    enable = true
    text = """As an engineering team lead of a startup, I lead the team to build our SaaS product from 0 to 1
    and is driven to keep the company growing by offering compelling new features and services to our customers.
    \nI am an experienced Golang developer and built several production services in Golang, and a DevOps engineer
    with experience in AWS, Terraform, and Kubernetes. To boost the efficiency of the team, I standardized the process
    of CI/CD, deployment, monitoring, alerting of our services, and shaped the DevOps culture among members.
    \nI love to participate in community activities and also share my knowledge with [blogs](https://blog.david74.dev) and
    [technical talks](https://speakerdeck.com/david74chou). Currently, I am the co-organizer of the Golang Taiwan community.
    """

    [params.education]
        enable = true

        [[params.education.list]]
        degree = "M.S in Computer Science"
        university = "National Chiao Tung University"
        dates = "2007 - 2009"
        [[params.education.list]]
        degree = "B.S in Computer Science"
        university = "National Chiao Tung University"
        dates = "2003 - 2007"

    [params.awards]
        enable = true

        [[params.awards.list]]
        name = "Publications"
        body = "[Scene change aware intra-frame rate control for H.264/AVC](https://ieeexplore.ieee.org/document/5604298)"
        date = "IEEE TCSVT, 2010"
        [[params.awards.list]]
        name = "Patents"
        body = "[System and method for streaming media](https://twpat-simple.tipo.gov.tw/tipotwoc/tipotwkm?!!FR_201916664)"
        date = "Taiwan invention patent"

    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "Chinese"
        level = "Native"
        [[params.languages.list]]
        name = "English"
        level = "Fluent"

    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Engineering Team Lead"
        dates = "2015 - 2021"
        company = "Umbo Computer Vision Inc."
        details = """Umbo is an A.I. startup that leverages machine learning and cloud technology to build
        autonomous video security systems for businesses. As a founding engineer, I participated in the whole
        architecture design and product implementation from scratch. As an engineering team lead, I mentored, sponsored
        and supported my members by shaping Umbo engineering culture. As a cloud architect, I committed to optimize
        infrastructure and improve work flow.
        """

        [[params.experience.list.items]]
        details = "Team management"
        [[params.experience.list.items.subs]]
        details = """**Led engineering team of 8 members**
        \nMy responsibilities included OKR planning, regular 1-1 feedback, mentoring, sponsoring, and hiring. I committed
        to build a responsible, transparent and keep-learning engineering team.
        """
        [[params.experience.list.items.subs]]
        details = """**Focused on team-wise productivity improvement**
        \nStandardized the development flow, introducing CI/CD and unit testing, adopting Infrastructure-as-code, and
        shaping DevOps culture in the team.
        """
        [[params.experience.list.items.subs]]
        details = """**Cross-team collaboration**
        \nFrequently co-worked with different teams, such as Design, Product and Sales, to help them from
        different approaches, such as studying competitor, discussing product roadmap, joining customer
        concalls, etc.
        """

        [[params.experience.list.items]]
        details = "Architect and engineering"
        [[params.experience.list.items.subs]]
        details = """**Low latency video streaming service (Golang)**
        \nDesigned and developed Umbo's video streaming service on a large scale across multiple regions. It was
        the core architecture of Umbo and served more than 7500 cameras with below 3 seconds latency.
        """
        [[params.experience.list.items.subs]]
        details = """**IoT messaging service (Golang)**
        \nDeveloped and maintained the core messaging service that provided real-time communication across devices by WebSocket
        and served all Umbo's cameras across 4 different regions.
        """
        [[params.experience.list.items.subs]]
        details = """**Launch a new product - Event Filter (Golang)**
        \nInvolved in the completed product lifecycle from market research, competitor studying, product
        design, development, and launching. Engineering-wise, I implemented 2 gateway services (SMTP and HTTP) and
        deployed to ECS Fargate with Terraform. As a result, it reduced 83% of false alarms for customers
        and boosted Umbo’s monthly recurring revenue (MRR) by 230%.
        """
        [[params.experience.list.items.subs]]
        details = """**Firmware applications development (C/C++)**
        \nInvolved in firmware architecture design and development. Designed a flexible cross-platform firmware
        architecture that helps us to deliver different camera models efficiently.
        """

        [[params.experience.list.items]]
        details = "Infrastructure and process optimization"
        [[params.experience.list.items.subs]]
        details = """**Standardlized production service deployment**
        \n Standardlized a consistent service deployment by using AWS ECS Fargate and Terraform. Different services
        could use the same way for secret management, log collection, monitoring, etc. It drastically reduced
        the operation loading and speeded up the launch of new services by 300%.
        """
        [[params.experience.list.items.subs]]
        details = """**Cross-services tracing solution**
        \nLed and supported the team to build a cross-services tracing by leveraging NewRelic tracing service. It gave
        us a clear view of end-to-end latency, and we built monitoring and alerting based on the metrics.
        """
        [[params.experience.list.items.subs]]
        details = """**Optimize AWS infrastructure costs**
        \nLed and supported the team to continuously optimize AWS costs. I regularly reviewed AWS cost analysis and proposed
        different approaches, including EC2/Fargate Spot and ARM instance adoption, NAT and cross-zone traffic reduction,
        S3 lifecycle optimization. As a result, we reduced 54% AWS system cost under the same business scale.
        """
        [[params.experience.list.items.subs]]
        details = """**Internal infrastructure administration**
        \nAs an AWS architect of the team, I managed shared resources, such as IAM, VPC, purchasing RI/saving plan,
        building common AMI. I migrated internal services (e.g., Grafana, Sentry, ETL jobs) to EKS by using
        Terraform and Helm. I also optimized the performance of the log collection pipeline by fine-tuning Fluentd
        aggregator and ElasticSearch.
        """

        [[params.experience.list]]
        title = "Senior Engineer"
        dates = "2013 - 2015"
        company = "Trend Micro Inc."
        details = """Joined the new industrial control system (ICS) solution team in the early stage, and experienced
        the whole product development cycle from planning, development, shipping, and maintenance.
        """
        [[params.experience.list.items]]
        details = "[Trend Micro Safe Lock](https://www.trendmicro.com/zh_tw/business/products/user-protection/sps/endpoint/safe-lock.html)"
        [[params.experience.list.items.subs]]
        details = "A standalone system lockdown software for fixed-function devices."
        [[params.experience.list.items.subs]]
        details = "Developed the backend REST API service."
        [[params.experience.list.items]]
        details = "[Trend Micro Portable Security](https://www.trendmicro.com/ja_jp/business/products/user-protection/sps/endpoint/portable-security-3.html)"
        [[params.experience.list.items.subs]]
        details = "A malware scanning and cleanup tool for standalone PC or closed system."
        [[params.experience.list.items.subs]]
        details = "Designed and developed this product from the fundamental core module to user interface."

        [[params.experience.list]]
        title = "Senior Engineer"
        dates = "2009 - 2012"
        company = "CyberLink Corp."
        details = """I worked on video decoder and new features development for H.264, MPEG2, and VC1. The video
        decoder is the core module in the company and has been integrated into all products.
        """
        [[params.experience.list.items]]
        details = "Maintained the quality of video decoder module."
        [[params.experience.list.items]]
        details = "Performance tuning with SSE/Intrinsic **SIMD optimization**."
        [[params.experience.list.items]]
        details = "Developed hardware decoding for **H.264**, Motion JPEG decoding using **hardware acceleration**."

    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "[lambda-extension-log-shipper](https://github.com/david7482/lambda-extension-log-shipper)"
        meta = "Golang / Lambda"
        tagline = """Ship your Lambda logs directly to any destination and bypass Cloudwatch Logs. This is my
        **personal project** that works like a sidecar of the Lambda function. It would listen to your Lambda function
        logs by Lambda Logs API, so you could ship the logs to a custom destination without CloudWatch Logs
        and **save cost**.
        """

        [[params.projects.list]]
        title = "[terraform-provider-aws](https://github.com/hashicorp/terraform-provider-aws)"
        meta = "Golang / Terraform"
        tagline = """A well-known terraform plugin to provision AWS resources. I contributed the **EKS taint support**
        in the Managed Node Group resource.
        """

        [[params.projects.list]]
        title = "[telegraf](https://github.com/influxdata/telegraf)"
        meta = "Golang"
        tagline = """A popular opensource metrics collection agent from influxdata. I contributed a **performance optimization**
        in its AWS Cloudwatch integration.
        """

    [params.talks]
        enable = true
        details = """Given technical talks in several meetups and conferences, such as COSCUP, Google I/O Extended Taipei,
        iThome Gopher Day, Golang Taiwan Meetup, and Taiwan Streaming Meetup, topics including golang, software testing,
        centralized logging, and video codec. Slides: https://speakerdeck.com/david74chou
        """

        [[params.talks.list]]
        details="Fuzzy test in Go @ COSCUP 2021"
        [[params.talks.list]]
        details="Let's talk about testing in Go @ COSCUP 2020"
        [[params.talks.list]]
        details="Centralized Logging Solution using FireLens and Fluent Bit for ECS @ AWS Workshop 2020"
        [[params.talks.list]]
        details="How the Go runtime implement map efficiently @ Golang Taiwan Meetup 2018"
        [[params.talks.list]]
        details="AV1: The next generation video codec @ Taiwan Streaming Meetup 2018"
        [[params.talks.list]]
        details="Golang execution modes @ iThome Gopher Day 2017"
        [[params.talks.list]]
        details="Building microservice with gRPC in Golang @ Google I/O Extended Taipei 2017"

    [params.information]
        enable = true

        [[params.information.list]]
        title = "Development"
        [[params.information.list.items]]
        details = "**Languages:** Golang, C/C++, Java, C#"
        [[params.information.list.items]]
        details = "**Databases:** MySQL, MongoDB, Etcd"
        [[params.information.list.items]]
        details = "**Protocols:** HTTP, Websocket, gRPC, SMTP"

        [[params.information.list]]
        title = "Operations"
        [[params.information.list.items]]
        details = "**AWS:** S3, EC2, ECS, EKS, SQS, VPC, IAM, Lambda, EventBridge, Cloudfront, etc"
        [[params.information.list.items]]
        details = "**Container Orchestration:** Kubernetes, ECS"
        [[params.information.list.items]]
        details = "**IaC:** Terraform, Helm, Packer, Ansible, Serverless"
        [[params.information.list.items]]
        details = "**CI/CD:** Jenkins, Github Action"
        [[params.information.list.items]]
        details = "**Monitoring & Logs:** Telegraf, Prometheus, Grafana, Fluentd, Fluentbit, Elasticsearch, Kibana, New Relic"

        [[params.information.list]]
        title = "Multimedia"
        [[params.information.list.items]]
        details = "**Codecs:** H.264"
        [[params.information.list.items]]
        details = "**Container:** MP4, fMP4"
        [[params.information.list.items]]
        details = "**Streaming:** RTSP, HLS, DASH"
        [[params.information.list.items]]
        details = "**Frameworks:** FFMPEG, Live555, GStreamer"
        [[params.information.list.items]]
        details = "**Acceleration:** DxVA, SIMD"

        [[params.information.list]]
        title = "Others"
        [[params.information.list.items]]
        details = "**Source Control:** Git, SVN"
        [[params.information.list.items]]
        details = "**Build System:** Make, CMake"
        [[params.information.list.items]]
        details = "**Project Management:** JIRA, Confluence, Trello"

    [params.footer]
        copyright = "David Chou"