baseURL = "https://me.david74.dev"
languageCode = "en"
title = ""
theme = "hugo-devresume-theme"
googleAnalytics = "UA-XXXXXXX-Y"

[params]
    author = "David Chou"
    primaryColor = "#54B689"
    textPrimaryColor = "#292929"

    [params.profile]
        enable = true
        name = "Ting-Li Chou"
        tagline = ""
        avatar = "avatar.png"

    [params.contact]
        enable = true
        location = "Taipei, Taiwan"

        [[params.contact.list]]
        icon = "fas fa-envelope"
        url = "mailto:david74.chou@gmail.com"
        text = "david74.chou@gmail.com"
        [[params.contact.list]]
        icon = "fab fa-linkedin"
        url = "https://www.linkedin.com/in/ting-li-chou-55393662/"
        text = "Ting-Li Chou"
        [[params.contact.list]]
        icon = "fab fa-github"
        url = "https://github.com/david7482"
        text = "github.com/david7482"
        [[params.contact.list]]
        icon = "fab fa-medium"
        url = "https://blog.david74.dev"
        text = "blog.david74.dev"
        [[params.contact.list]]
        icon = "fab fa-slideshare"
        url = "https://www.slideshare.net/david74chou/presentations"
        text = "slideshare"

    [params.summary]
    enable = true
    text = """As a developer team lead of a startup, I lead the team to build our SaaS product from 0 to 1,
    and being driven to keep the company growth via offering compelling new features and services to our customers.
    I am an experienced Golang developer and built several production services in Golang, and a DevOps
    engineer with experience in AWS, Terraform, and Kubernetes. I love to participate in community activities and
    also share my knowledge. Currently, I am the co-organizer of Golang Taiwan community.
    """

    [params.education]
        enable = true

        [[params.education.list]]
        degree = "M.S in Computer Science"
        university = "National Chiao Tung University"
        dates = "2007 - 2009"
        [[params.education.list]]
        degree = "B.S in Computer Science"
        university = "National Chiao Tung University"
        dates = "2003 - 2007"

    [params.awards]
        enable = true

        [[params.awards.list]]
        name = "Award Lorem Ipsum"
        body = "Microsoft lorem ipsum"
        date = "2019"
        [[params.awards.list]]
        name = "Award Donec Sodales"
        body = "Oracle Aenean"
        date = "2017"

    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "Chinese"
        level = "Native"
        [[params.languages.list]]
        name = "English"
        level = "Fluent"

    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Senior Software Engineer"
        dates = "2019 - Present"
        company = "Google"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Donec pede justo, fringilla vel. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis."
        [[params.experience.list.items]]
        details = "Lorem ipsum dolor sit amet, consectetuer."
        [[params.experience.list.items]]
        details = "Aenean commodo ligula eget dolor."
        [[params.experience.list.items]]
        details = "Etiam ultricies nisi vel augue."

        [[params.experience.list]]
        title = "Lead Software Developer"
        dates = "2016 - 2019"
        company = "Apple"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Donec pede justo, fringilla vel."
        [[params.experience.list.items]]
        details = "Lorem ipsum dolor sit amet, consectetuer."
        [[params.experience.list.items]]
        details = "Aenean commodo ligula eget dolor."

        [[params.experience.list]]
        title = "Senior Software Developer"
        dates = "2014 - 2016"
        company = "Dropbox"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.experience.list]]
        title = "Senior Developer"
        dates = "2013 - 2014"
        company = "Uber"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus."

        [[params.experience.list]]
        title = "Backend Developer"
        dates = "2014 - 2016"
        company = "Amazon"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.experience.list]]
        title = "Frontend Developer"
        dates = "2013 - 2014"
        company = "Startup"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus."

    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "Project Lorem Ipsum"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.projects.list]]
        title = "Project Sed Fringilla"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."

        [[params.projects.list]]
        title = "Project Praesent"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."

    [params.information]
        enable = true

        [[params.information.list]]
        title = "Development"
        [[params.information.list.items]]
        details = "**Languages:** Golang, C/C++, Java, C#"
        [[params.information.list.items]]
        details = "**Databases:** MySQL, MongoDB, etcd"
        [[params.information.list.items]]
        details = "**Protocols:** HTTP, Websocket, gRPC, SMTP"

        [[params.information.list]]
        title = "Operations"
        [[params.information.list.items]]
        details = "**AWS:** S3, EC2, ECS, EKS, VPC, Cloudfront, Lambda"
        [[params.information.list.items]]
        details = "**Container Orchestration:** Kubernetes, ECS"
        [[params.information.list.items]]
        details = "**IaC:** Terraform, Helm, Packer, Ansible, Serverless"
        [[params.information.list.items]]
        details = "**CI/CD:** Jenkins, Github Action"
        [[params.information.list.items]]
        details = "**Logs:** Fluentd, Fluentbit, Elasticsearch, Kibana"
        [[params.information.list.items]]
        details = "**Metrics:** Telegraf, Prometheus, Grafana"

        [[params.information.list]]
        title = "Multimedia"
        [[params.information.list.items]]
        details = "**Codecs:** H.264"
        [[params.information.list.items]]
        details = "**Container:** MP4, fMP4"
        [[params.information.list.items]]
        details = "**Streaming:** RTSP, HLS, DASH"
        [[params.information.list.items]]
        details = "**Framework:** FFMPEG, Live555, GStreamer"
        [[params.information.list.items]]
        details = "**Acceleration:** DxVA, SIMD"

        [[params.information.list]]
        title = "Others"
        [[params.information.list.items]]
        details = "**Source Control:** Git, SVN"
        [[params.information.list.items]]
        details = "**Project Management:** JIRA, Trello, Confluence"

    [params.footer]
        copyright = "David Chou"